export const APPLICATION_STATUS = Object.freeze({
  APPLIED: "applied",
  SCREENING: "screening",
  SHORTLISTED: "shortlisted",
  INTERVIEW: "interview",
  SELECTED: "selected",
  REJECTED: "rejected",
  HIRED: "hired",
});

export const APPLICATION_STATUS_ORDER = [
  APPLICATION_STATUS.APPLIED,
  APPLICATION_STATUS.SCREENING,
  APPLICATION_STATUS.SHORTLISTED,
  APPLICATION_STATUS.INTERVIEW,
  APPLICATION_STATUS.SELECTED,
  APPLICATION_STATUS.HIRED,
];

export const APPLICATION_STATUS_LABELS = {
  [APPLICATION_STATUS.APPLIED]: "Applied",
  [APPLICATION_STATUS.SCREENING]: "Screening",
  [APPLICATION_STATUS.SHORTLISTED]: "Shortlisted",
  [APPLICATION_STATUS.INTERVIEW]: "Interview",
  [APPLICATION_STATUS.SELECTED]: "Selected",
  [APPLICATION_STATUS.REJECTED]: "Rejected",
  [APPLICATION_STATUS.HIRED]: "Hired",
};
