// Spatie permission strings
export const PERMISSIONS = Object.freeze({
  USERS_MANAGE: "users.manage",
  USERS_SUSPEND: "users.suspend",
  USERS_INVITE: "users.invite",
  COMPANIES_MANAGE: "companies.manage",
  DEPARTMENTS_MANAGE: "departments.manage",
  DEPARTMENTS_VIEW: "departments.view",
  JOBS_CREATE: "jobs.create",
  JOBS_EDIT: "jobs.edit",
  JOBS_CLOSE: "jobs.close",
  JOBS_VIEW: "jobs.view",
  HIRING_MANAGE: "hiring.manage",
  REPORTS_EXPORT: "reports.export",
  APPLICATIONS_VIEW: "applications.view",
  APPLICATIONS_SCREEN: "applications.screen",
  APPLICATIONS_CREATE: "applications.create",
  INTERVIEWS_MANAGE: "interviews.manage",
  CANDIDATE_NOTES_CREATE: "candidate.notes.create",
  CANDIDATES_VIEW: "candidates.view",
  RESUMES_VIEW: "resumes.view",
  SKILLS_MANAGE: "skills.manage",
  FAQ_MANAGE: "faq.manage",
  PROFILE_MANAGE: "profile.manage",
  RESUME_UPLOAD: "resume.upload",
  APPLICATIONS_SELF_VIEW: "applications.self.view",
});

export const ROLE_PERMISSIONS = Object.freeze({
  admin: Object.values(PERMISSIONS),
  hr_manager: [
    PERMISSIONS.JOBS_CREATE,
    PERMISSIONS.JOBS_EDIT,
    PERMISSIONS.JOBS_CLOSE,
    PERMISSIONS.JOBS_VIEW,
    PERMISSIONS.HIRING_MANAGE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.INTERVIEWS_MANAGE,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.CANDIDATES_VIEW,
    PERMISSIONS.RESUMES_VIEW,
  ],
  recruiter: [
    PERMISSIONS.JOBS_VIEW,
    PERMISSIONS.APPLICATIONS_SCREEN,
    PERMISSIONS.INTERVIEWS_MANAGE,
    PERMISSIONS.CANDIDATE_NOTES_CREATE,
    PERMISSIONS.CANDIDATES_VIEW,
    PERMISSIONS.RESUMES_VIEW,
  ],
  candidate: [
    PERMISSIONS.PROFILE_MANAGE,
    PERMISSIONS.RESUME_UPLOAD,
    PERMISSIONS.APPLICATIONS_SELF_VIEW,
    PERMISSIONS.APPLICATIONS_CREATE,
    PERMISSIONS.JOBS_VIEW,
  ],
});
