name: Frontend CI

on:
  push:
    paths:
      - "front-end/**"
      - ".github/workflows/frontend.yml"

  pull_request:
    paths:
      - "front-end/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front-end

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "VITE_API_BASE_URL=http://localhost:8000/api/v1" > .env

      - name: Run ESLint
        run: npm run lint

      - name: Build application
        run: npm run build